version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: nuget restore RefAnalyzer/RefAnalyzer.sln
build:
  project: RefAnalyzer/RefAnalyzer.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
artifacts:
- path: RefAnalyzer\RefAnalyzer\bin\Debug\UnityRefAnalyzer.*.nupkg
  name: NuGet
