version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: nuget restore RefAnalyzer/RefAnalyzer.sln
build:
  project: RefAnalyzer/RefAnalyzer.sln
  verbosity: minimal